os: osx
osx_image: xcode10.1
language: swift
script: xcodebuild clean build test -project CodingExercise.xcodeproj -scheme CodingExercise -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.0' ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
os: osx. // We need to use Mac OS, as we are developing on Mac.
osx_imageB: xcode10.1 // We are specifically specifying on which version of XCode we need to build our code.
language: swift // Here we are specifying the default language of our project.
script // This script will run when travis-ci will build our app.